### ISSUE TITLE
Start using gitflow and semver release tagging

### ISSUE THREAD

**Issue by loudnate** [ps2/rileylink_ios#10]
Sorry to feel so corporate, but as more folks start to use the app, some structure will help master be unbroken :innocent:

**Comment by ps2** [comment]
No apologies needed.  It's a good idea.  Need to version the firmware as well.

**Comment by loudnate** [comment]
In other projects, I bump `CFBundleVersion` each time an archive operation is run using a script. I'd we could bump it on each build, but that will cause unnecessary merge conflicts since we're not using a centralized build server. For now I think we'll increment each of `CFBundleVersion`, `CFBundleShortVersionString`, and `RileyLink.podspec` by hand after each `dev` branch merge.

If you're up for writing a ruby command-line script to keep all three in sync, that'd be great (I am quite rusty in ruby myself), and I can configure it as part of the build process.

**Comment by ps2** [comment]
Were you thinking the ruby script would just verify that things were in sync, or actually take the RileyLink-Info.plist key and update the podspec?  Or look at the podspec and update the plist?

**Comment by ps2** [comment]
Notes: plutil can update plists, and we can turn the podspec into json with pod ipc spec

**Comment by loudnate** [comment]
It's probably easier to make Info.plist canon, specifically CFBundleShortVersionString since it has a friendly UI in the project inspector.
