### ISSUE TITLE
Reinstate ability to give individual rileylinks custom names.

### ISSUE THREAD

**Issue by ps2** [ps2/rileylink_ios#114]
Maybe just a new textfield on the page after you click on the rileylink in the rileylink list.

**Comment by loudnate** [comment]
+1, Name Row -> TextFieldViewController should make this a snap.

**Comment by loudnate** [comment]
Works for me! I did cause it to silently fail on first try by using an apostrophe character. What are the valid characters? I can add a filter in the text field's delegate.

**Comment by loudnate** [comment]
Fixed in v0.6.0
