### ISSUE TITLE
Decoding of carbs in meal marker is incorrect

### ISSUE THREAD

**Issue by ecc1** [ps2/rileylink_ios#198]
In JournalEntryMealMarkerPumpEvent.swift, bit 9 of the carb value is taken from the low bit of data[8], but it should be taken from the low bit of data[1]. 

For example, this is the record for a 10g carb entry: 40 00 93 27 10 10 10 0A 01
and this is the record for a 299g carb entry: 40 01 87 37 12 10 10 2B 01

I'm not sure yet what the 01 in data[8] means.

**Comment by ecc1** [comment]
02 means exchanges, so it seems like 01 just means grams (so carb unit type is enumerated 1,2, rather than a bit that's set)

**Comment by ps2** [comment]
Thanks, Eric!
