### ISSUE TITLE
Ability to use MM CGM with an x22 Pump

### ISSUE THREAD

**Issue by tomasboudr** [ps2/rileylink_ios#200]
Looking for the ability to use a MM CGM with an x22 pump, thus we will need to parse sensor data pages in rileylink

Related issue in Loop: https://github.com/loudnate/Loop/issues/100

**Comment by ps2** [comment]
See getHistoryEvents in https://github.com/ps2/rileylink_ios/blob/dev/RileyLinkKit/PumpOpsSynchronous.swift for an example of the swift code you'll need to write to fetch the pages

**Comment by ps2** [comment]
@bewest  has Python code to decode CGM pages here: https://github.com/openaps/decocare/blob/master/decocare/cgm/__init__.py

**Comment by tmecklem** [comment]
I'm spiking a solution to this at https://github.com/tmecklem/rileylink_ios/tree/support-paged-cgm.

**Comment by ps2** [comment]
Support for fetching CGM pages has been merged in.  Still not uploading CGM data to NS.

**Comment by ps2** [comment]
Fixed with #275
