### ISSUE TITLE
Upload suspend and unsuspend events to NS

### ISSUE THREAD

**Issue by ps2** [ps2/rileylink_ios#205]
These events are not yet handled in NS, but they are important for remote monitoring.

**Comment by loudnate** [comment]
I assume the goal is to upload as-raw-as-possible pump data, and any analysis/reconciliation of that pump data into actual insulin delivery would happen in Nightscout?

**Comment by ps2** [comment]
Yes, I think so. I would like to make it work without too much difficulty with the temp basal display. I think storing it as another treatments.json record makes sense and would work with the existing code in NS well.

**Comment by loudnate** [comment]
gotcha. I've got a slew of unit test fixtures for properly reconciling that data if you need it.

**Comment by ps2** [comment]
Is that https://github.com/loudnate/openaps-mmhistorytools ?

**Comment by loudnate** [comment]
And https://github.com/loudnate/LoopKit/tree/master/InsulinKitTests

**Comment by ps2** [comment]
Fixed with #306
