### ISSUE TITLE
Get events for saving settings.

### ISSUE THREAD

**Issue by ps2** [ps2/rileylink_ios#209]
Figure out history event codes for restore settings and clear settings

**Comment by loudnate** [comment]
Intersting, what happens in a restore settings case?

**Comment by ps2** [comment]
CC @sarahspins

**Comment by ps2** [comment]
A lot of unknown records is what happens. :)

**Comment by loudnate** [comment]
Haha I meant from a pump perspective.

**Comment by ps2** [comment]
Resolved with #210
