### ISSUE TITLE
Ensure central manager is powered on before subscribing to characteristics

### ISSUE THREAD

**Issue by loudnate** [ps2/rileylink_ios#22]
When the app is re-launched in the background, the central manager's state is restored with "connected" peripherals, before the CBCentralManagerState is powered on. Writing, reading, or subscribing to characteristics during that time results in the following warning:

```
Sep  4 18:36:04 Nates-iPhone-6 Naterade[4360] <Warning>: (Warn ) CoreBluetooth: API MISUSE: <CBCentralManager: 0x170269000> can only accept this command while in the powered on state
```

**Comment by ps2** [comment]
I believe this is resolved, no?

**Comment by loudnate** [comment]
No, I still haven't gotten around to it. Other than a console error of "API
MISUSE" on app startup, there's no other side effects (at this time).

**Comment by ps2** [comment]
Fixed in iOS 11 patch.
