### ISSUE TITLE
Poll Pump History

### ISSUE THREAD

**Issue by ps2** [ps2/rileylink_ios#37]
Poll pump history, and extract treatments, meter bg, etc.

**Comment by loudnate** [comment]
I've been thinking a lot about this, and I'm not sure there's enough background quota to manage the pump power wake and download history. What do you think about moving power control to the firmware, with a write/notify characteristic when it's on?

**Comment by ps2** [comment]
I think that's a good idea from a system design perspective (and maybe necessary, as you point out).  The two things I don't like about it are: 1. we have to write it in bgscript, and 2. lots of users don't have the ability to upgrade firmware. But those are perhaps just unpleasant realities we need to accept. :)

**Comment by loudnate** [comment]
Yeah, and maybe I'm putting the cart before the horse. 

In between reverse-engineering the G5, I have started to work on a process for incremental updates of pump history, marking records as final or mutable. Each page of history we can avoid will save a lot of time (and potential error). 

For someone like me who is auto-issuing temp basals, the history pages fill really fast, so this will be a benefit even on a carelink setup.

**Comment by ps2** [comment]
Which records in pump history are mutable?

**Comment by loudnate** [comment]
Bolus records (normal and square) are, though bolus cancellation is sufficiently rare. 

TempBasal records aren't mutable but can be superseded.

**Comment by ps2** [comment]
How would one mutate a bolus record after the fact?

**Comment by loudnate** [comment]
bolus records (square and normal) keep track of the amount delivered, and and update it during the dose.

**Comment by ps2** [comment]
I think we have the methods called for at this layer.  History reconciliation is another layer, I think.
