### ISSUE TITLE
OmniKit - Pod Error When Trying "Test Set Temp Basal"

### ISSUE THREAD

**Issue by mawaji1** [ps2/rileylink_ios#410]
I activated a new Pod using [Barnacleboy](https://github.com/barnacleboy/rileylink_ios/tree/omnikit) hardcoded basal setting and was able to successfully pair a new Pod. However, when I tried the "Test Set Temp Basal" functionality, the Pod just failed instantly and I couldn't even deactivate it using OmniKit. Attached is the Xcode log file. 

Here is my basal settings that were used in this build:

```
 let schedule = BasalSchedule(entries:
               [BasalScheduleEntry(rate: 1.5, duration: .hours(16)),
                BasalScheduleEntry(rate: 1.7, duration: .hours(8))
                ])
```

[Test_TempBasal_Error.txt](https://github.com/ps2/rileylink_ios/files/2118308/Test_TempBasal_Error.txt)

**Comment by ps2** [comment]
This is from setting two temp basals in a row without canceling the first. The first was set via the testing command.
