### ISSUE TITLE
OmniKit: Deactivate Pod command is missing an alert settings reset

### ISSUE THREAD

**Issue by Lytrix** [ps2/rileylink_ios#453]
The Deactivate Pod command does not stop the 80hr expiration alarm, causing a deactivated pod to still scream after a while.

**Comment by ps2** [comment]
Could you post an example of the command that is set during deactivation?
We do send a $1c (deactivatePod).  Looking at the example captures of deactivation, I don't see a configureAlerts $19 command.

**Comment by Lytrix** [comment]
I also do not see any $19 command, this is probably set more specifically at the priming stage. 
But I want to test ending a pod by also sending the $46 $50 and $51 commands, to see if that does anything.

**Comment by ps2** [comment]
I think this ticket is probably more an artifact of the fact that the changePod() call wasn't being made at all, when the user tapped Deactivate Pod in the UI.  It is now: https://github.com/ps2/rileylink_ios/blob/dev/OmniKitUI/OmnipodSettingsViewController.swift#L319

**Comment by Lytrix** [comment]
Ah yes, there was indeed no changePod() action called. Great, will test this soon when I start recording all the different pod info types probably this weekend.

**Comment by Lytrix** [comment]
Deactivation now works properly with the added fault event  fallback, thanks!
