### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by sumairs** [ps2/rileylink_ios#693]
I got a bunch of build errors when applying the patch to loop V2.2.6. I have an OL Pro FW3.2/HW1.1
<img width="1023" alt="Screen Shot 2022-01-05 at 6 24 54 PM" src="https://user-images.githubusercontent.com/57295742/148304093-bc997e49-5953-46af-939e-40d6c344d13b.png">
.
<img width="1396" alt="Screen Shot 2022-01-05 at 6 22 28 PM" src="https://user-images.githubusercontent.com/57295742/148304098-54b265e7-4369-4df6-be3c-2b7900f80f0a.png">

Any idea what I am doing wrong?

**Comment by razzfox** [comment]
@sumairs How did you fix this error?
