### ISSUE TITLE
Assert PumpModel string in PumpState for more comms

### ISSUE THREAD

**Issue by loudnate** [ps2/rileylink_ios#74]
And manage a signal to trigger serializing PumpState after model/timeZone changes.

**Comment by loudnate** [comment]
Thinking through how best to notify observers of PumpState changes today.
KVO is the right paradigm, but it means quite a bit of boilerplate for observers, and it feels so archaic in Swift. It also requires the observer to extend `NSObject`, which I'd like to avoid.
Beyond that, it's really either rolling our own interface:

``` swift
addObserver((keyName: String, oldValue: Any?, newValue: Any?) -> Void) -> ObserverID
removeObserver(ObserverID)
```

Or using `NSNotificationCenter`, which is a little more heavyweight but doesn't add a custom variation on a concept.

**Comment by ps2** [comment]
I like the idea of KVO, but find it unwieldy in practice.  And we're already using NSNotifications everywhere, right?

**Comment by loudnate** [comment]
Yeah, we are, but I'm looking into move a few of those back to simple delegation where 1-M relationships aren't necessary. I believe `PumpState` has the need for multiple observers, however, so I think I'll start there.
